version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase                  
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipment data
        columns:
          - name: orders_id
            description: Primary key of the shipment table
            tests:
              - unique
              - not_null
      - name: adwords
        identifier:  raw_gz_adwords
        description: table with campaign data
        columns:
          - name: campaign_key
            description: it repeats but needs to be concatenated with date_date
            tests:
              - not_null
      - name: bing
        identifier:  raw_gz_bing
        description: table with bing campaign data
        columns:
          - name: campaign_key
            description: it repeats but needs to be concatenated with date_date
            tests:
              - not_null
      - name: criteo
        identifier:  raw_gz_criteo
        description: table with campaign data
        columns:
          - name: campaign_key
            description: it repeats but needs to be concatenated with date_date
            tests:
              - not_null
      - name: facebook
        identifier:  raw_gz_facebook
        description: table with campaign data
        columns:
          - name: campaign_key
            description: it repeats but needs to be concatenated with date_date
            tests:
              - not_null